export const DEMO_VIDEOS = [
  {
    id: "steve-jobs-stanford",
    title: "Steve Jobs' 2005 Stanford Commencement Address",
    channel: "Stanford",
    duration: 904, // 15:04
    url: "https://www.youtube.com/watch?v=UF8uR6Z6KLc",
    videoId: "UF8uR6Z6KLc",
    thumbnailUrl: "https://img.youtube.com/vi/UF8uR6Z6KLc/maxresdefault.jpg",
    transcript: [
      { start: 0.0, duration: 3.5, text: "I am honored to be with you today at your commencement from one of the finest universities in the world." },
      { start: 3.5, duration: 3.0, text: "Truth be told, I never graduated from college." },
      { start: 6.5, duration: 4.0, text: "And this is the closest I've ever gotten to a college graduation." },
      { start: 10.5, duration: 4.5, text: "Today, I want to tell you three stories from my life. That's it. No big deal. Just three stories." },
      { start: 15.0, duration: 2.0, text: "The first story is about connecting the dots." },
      { start: 17.0, duration: 5.0, text: "I dropped out of Reed College after the first 6 months, but then stayed around as a drop-in for another 18 months or so before I really quit." },
      { start: 22.0, duration: 2.5, text: "So why did I drop out?" },
      { start: 24.5, duration: 5.5, text: "It started before I was born. My biological mother was a young, unwed college graduate student, and she decided to put me up for adoption." },
      { start: 30.0, duration: 5.0, text: "She felt very strongly that I should be adopted by college graduates, so everything was all set for me to be adopted at birth by a lawyer and his wife." },
      { start: 35.0, duration: 6.0, text: "Except that when I popped out, they decided at the last minute that they really wanted a girl." },
      { start: 41.0, duration: 5.0, text: "So my parents, who were on a waiting list, got a call in the middle of the night asking: 'We have an unexpected baby boy; do you want him?'" },
      { start: 46.0, duration: 2.0, text: "They said: 'Of course.'" },
      { start: 48.0, duration: 6.0, text: "My biological mother later found out that my mother had never graduated from college and that my father had never graduated from high school." },
      { start: 54.0, duration: 4.0, text: "She refused to sign the final adoption papers. She only relented a few months later when my parents promised that I would someday go to college." },
      { start: 58.0, duration: 4.0, text: "And 17 years later I did go to college." },
      { start: 62.0, duration: 5.0, text: "But I naively chose a college that was almost as expensive as Stanford, and all of my working-class parents' savings were being spent on my college tuition." },
      { start: 67.0, duration: 4.0, text: "After six months, I couldn't see the value in it. I had no idea what I wanted to do with my life and no idea how college was going to help me figure it out." },
      { start: 71.0, duration: 4.0, text: "And here I was spending all of the money my parents had saved their entire life. So I decided to drop out and trust that it would all work out OK." },
      { start: 75.0, duration: 4.0, text: "It was pretty scary at the time, but looking back it was one of the best decisions I ever made." },
      { start: 79.0, duration: 6.0, text: "The minute I dropped out I could stop taking the required classes that didn't interest me, and begin dropping in on the ones that looked interesting." },
      { start: 85.0, duration: 5.0, text: "It wasn't all romantic. I didn't have a dorm room, so I slept on the floor in friends' rooms, I returned coke bottles for the 5¢ deposits to buy food with," },
      { start: 90.0, duration: 5.0, text: "and I would walk the 7 miles across town every Sunday night to get one good meal a week at the Hare Krishna temple. I loved it." },
      { start: 95.0, duration: 5.0, text: "And much of what I stumbled into by following my curiosity and intuition turned out to be priceless later on. Let me give you one example:" },
      { start: 100.0, duration: 6.0, text: "Reed College at that time offered perhaps the best calligraphy instruction in the country. Throughout the campus every poster, every label on every drawer, was beautifully hand calligraphed." },
      { start: 106.0, duration: 5.0, text: "Because I had dropped out and didn't have to take the normal classes, I decided to take a calligraphy class to learn how to do this." },
      { start: 111.0, duration: 6.0, text: "I learned about serif and sans serif typefaces, about varying the amount of space between different letter combinations, about what makes great typography great." },
      { start: 117.0, duration: 4.0, text: "It was beautiful, historical, artistically subtle in a way that science can't capture, and I found it fascinating." },
      { start: 121.0, duration: 5.0, text: "None of this had even a hope of any practical application in my life. But 10 years later, when we were designing the first Macintosh computer, it all came back to me." },
      { start: 126.0, duration: 4.0, text: "And we designed it all into the Mac. It was the first computer with beautiful typography." },
      { start: 130.0, duration: 5.0, text: "If I had never dropped in on that single course in college, the Mac would have never had multiple typefaces or proportionally spaced fonts." },
      { start: 135.0, duration: 5.0, text: "And since Windows just copied the Mac, it's likely that no personal computer would have them." },
      { start: 140.0, duration: 5.0, text: "If I had never dropped out, I would have never dropped in on this calligraphy class, and personal computers might not have the wonderful typography that they do." },
      { start: 145.0, duration: 4.0, text: "Of course it was impossible to connect the dots looking forward when I was in college. But it was very, very clear looking backward 10 years later." },
      { start: 149.0, duration: 5.0, text: "Again, you can't connect the dots looking forward; you can only connect them looking backward." },
      { start: 154.0, duration: 4.0, text: "So you have to trust that the dots will somehow connect in your future. You have to trust in something — your gut, destiny, life, karma, whatever." },
      { start: 158.0, duration: 4.0, text: "This approach has never let me down, and it has made all the difference in my life." },
      
      { start: 162.0, duration: 3.0, text: "My second story is about love and loss." },
      { start: 165.0, duration: 5.0, text: "I was lucky — I found what I loved to do early in life. Woz and I started Apple in my parents' garage when I was 20." },
      { start: 170.0, duration: 5.0, text: "We worked hard, and in 10 years Apple had grown from just the two of us in a garage into a $2 billion company with over 4000 employees." },
      { start: 175.0, duration: 5.0, text: "We had just released our finest creation — the Macintosh — a year earlier, and I had just turned 30. And then I got fired." },
      { start: 180.0, duration: 3.0, text: "How can you get fired from a company you started?" },
      { start: 183.0, duration: 6.0, text: "Well, as Apple grew we hired someone who I thought was very talented to run the company with me, and for the first year or so things went well." },
      { start: 189.0, duration: 5.0, text: "But then our visions for the future began to diverge and eventually we had a falling out. When we did, our Board of Directors sided with him." },
      { start: 194.0, duration: 5.0, text: "So at 30 I was out. And very publicly out. What had been the focus of my entire adult life was gone, and it was devastating." },
      { start: 199.0, duration: 5.0, text: "I really didn't know what to do for a few months. I felt that I had let the previous generation of entrepreneurs down - that I had dropped the baton as it was being passed to me." },
      { start: 204.0, duration: 6.0, text: "I met with David Packard and Bob Noyce and tried to apologize for screwing up so badly. I was a very public failure, and I even thought about running away from the valley." },
      { start: 210.0, duration: 5.0, text: "But something slowly began to dawn on me — I still loved what I did. The turn of events at Apple had not changed that one bit." },
      { start: 215.0, duration: 4.0, text: "I had been rejected, but I was still in love. And so I decided to start over." },
      { start: 219.0, duration: 5.0, text: "I didn't see it then, but it turned out that getting fired from Apple was the best thing that could have ever happened to me." },
      { start: 224.0, duration: 5.0, text: "The heaviness of being successful was replaced by the lightness of being a beginner again, less sure about everything. It freed me to enter one of the most creative periods of my life." },
      { start: 229.0, duration: 6.0, text: "During the next five years, I started a company named NeXT, another company named Pixar, and fell in love with an amazing woman who would become my wife." },
      { start: 235.0, duration: 5.0, text: "Pixar went on to create the world's first computer animated feature film, Toy Story, and is now the most successful animation studio in the world." },
      { start: 240.0, duration: 6.0, text: "In a remarkable turn of events, Apple bought NeXT, I returned to Apple, and the technology we developed at NeXT is at the heart of Apple's current renaissance." },
      { start: 246.0, duration: 3.0, text: "And Laurene and I have a wonderful family together." },
      { start: 249.0, duration: 5.0, text: "I'm pretty sure none of this would have happened if I hadn't been fired from Apple. It was awful tasting medicine, but I guess the patient needed it." },
      { start: 254.0, duration: 5.0, text: "Sometimes life hits you in the head with a brick. Don't lose faith." },
      { start: 259.0, duration: 5.0, text: "I'm convinced that the only thing that kept me going was that I loved what I did. You've got to find what you love." },
      { start: 264.0, duration: 6.0, text: "And that is as true for your work as it is for your lovers. Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work." },
      { start: 270.0, duration: 4.0, text: "And the only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle." },
      { start: 274.0, duration: 4.0, text: "As with all matters of the heart, you'll know when you find it. And, like any great relationship, it just gets better and better as the years roll on." },
      { start: 278.0, duration: 2.0, text: "So keep looking until you find it. Don't settle." },
      
      { start: 280.0, duration: 3.0, text: "My third story is about death." },
      { start: 283.0, duration: 5.0, text: "When I was 17, I read a quote that went something like: 'If you live each day as if it was your last, someday you'll most certainly be right.'" },
      { start: 288.0, duration: 5.0, text: "It made an impression on me, and for the past 33 years, I have looked in the mirror every morning and asked myself: 'If today were the last day of my life, would I want to do what I am about to do today?'" },
      { start: 293.0, duration: 4.0, text: "And whenever the answer has been 'No' for too many days in a row, I know I need to change something." },
      { start: 297.0, duration: 5.0, text: "Remembering that I'll be dead soon is the most important tool I've ever encountered to help me make the big choices in life." },
      { start: 302.0, duration: 6.0, text: "Because almost everything — all external expectations, all pride, all fear of embarrassment or failure - these things just fall away in the face of death, leaving only what is truly important." },
      { start: 308.0, duration: 4.0, text: "Remembering that you are going to die is the best way I know to avoid the trap of thinking you have something to lose. You are already naked. There is no reason not to follow your heart." },
      { start: 312.0, duration: 5.0, text: "About a year ago I was diagnosed with cancer. I had a scan at 7:30 in the morning, and it clearly showed a tumor on my pancreas. I didn't even know what a pancreas was." },
      { start: 317.0, duration: 5.0, text: "The doctors told me this was almost certainly a type of cancer that is incurable, and that I should expect to live no longer than three to six months." },
      { start: 322.0, duration: 5.0, text: "My doctor advised me to go home and get my affairs in order, which is doctor's code for prepare to die." },
      { start: 327.0, duration: 5.0, text: "It means to try to tell your kids everything you thought you'd have the next 10 years to tell them in just a few months. It means to make sure everything is buttoned up so that it will be as easy as possible for your family." },
      { start: 332.0, duration: 2.0, text: "It means to say your farewells." },
      { start: 334.0, duration: 5.0, text: "I lived with that diagnosis all day. Later that evening I had a biopsy, where they stuck an endoscope down my throat, through my stomach and into my intestines," },
      { start: 339.0, duration: 5.0, text: "put a needle into my pancreas and got a few cells from the tumor. I was sedated, but my wife, who was there, told me that when they viewed the cells under a microscope" },
      { start: 344.0, duration: 5.0, text: "the doctors started crying because it turned out to be a very rare form of pancreatic cancer that is curable with surgery. I had the surgery and I'm OK now." },
      { start: 349.0, duration: 4.0, text: "This was the closest I've been to facing death, and I hope it's the closest I get for a few more decades." },
      { start: 353.0, duration: 5.0, text: "Having lived through it, I can now say this to you with a bit more certainty than when death was a useful but purely intellectual concept:" },
      { start: 358.0, duration: 3.0, text: "No one wants to die. Even people who want to go to heaven don't want to die to get there." },
      { start: 361.0, duration: 4.0, text: "And yet death is the destination we all share. No one has ever escaped it. And that is as it should be, because Death is very likely the single best invention of Life." },
      { start: 365.0, duration: 4.0, text: "It is Life's change agent. It clears out the old to make way for the new." },
      { start: 369.0, duration: 5.0, text: "Right now the new is you, but someday not too long from now, you will gradually become the old and be cleared away. Sorry to be so dramatic, but it is quite true." },
      { start: 374.0, duration: 5.0, text: "Your time is limited, so don't waste it living someone else's life. Don't be trapped by dogma — which is living with the results of other people's thinking." },
      { start: 379.0, duration: 5.0, text: "Don't let the noise of others' opinions drown out your own inner voice. And most important, have the courage to follow your heart and intuition." },
      { start: 384.0, duration: 4.0, text: "They somehow already know what you truly want to become. Everything else is secondary." },
      { start: 388.0, duration: 5.0, text: "When I was young, there was an amazing publication called The Whole Earth Catalog, which was one of the bibles of my generation." },
      { start: 393.0, duration: 5.0, text: "It was created by a fellow named Stewart Brand not far from here in Menlo Park, and he brought it to life with his poetic touch." },
      { start: 398.0, duration: 5.0, text: "This was in the late 1960's, before personal computers and desktop publishing, so it was all made with typewriters, scissors, and polaroid cameras." },
      { start: 403.0, duration: 5.0, text: "It was sort of like Google in paperback form, 35 years before Google came along: it was idealistic, and overflowing with neat tools and great notions." },
      { start: 408.0, duration: 5.0, text: "Stewart and his team put out several issues of The Whole Earth Catalog, and then when it had run its course, they put out a final issue." },
      { start: 413.0, duration: 5.0, text: "It was the mid-1970s, and I was your age. On the back cover of their final issue was a photograph of an early morning country road, the kind you might find yourself hitchhiking on if you were so adventurous." },
      { start: 418.0, duration: 5.0, text: "Beneath it were the words: 'Stay Hungry. Stay Foolish.' It was their farewell message as they signed off." },
      { start: 423.0, duration: 2.0, text: "Stay Hungry. Stay Foolish." },
      { start: 425.0, duration: 4.0, text: "And I have always wished that for myself. And now, as you graduate to begin anew, I wish that for you." },
      { start: 429.0, duration: 3.0, text: "Stay Hungry. Stay Foolish." },
      { start: 432.0, duration: 2.0, text: "Thank you all very much." }
    ],
    notes: [
      {
        id: "sec-1",
        title: "Story 1: Connecting the Dots",
        timestamp: 15.0,
        summary: "Steve Jobs shares the story of dropping out of Reed College, how dropping in on calligraphy classes shaped the Macintosh computer, and why we must trust that the experiences in our lives will eventually connect.",
        bullets: [
          "Curiosity & Intuition: Dropping out of required classes freed him to follow his interests, which led him to learn calligraphy, the direct inspiration for beautiful typography on personal computers.",
          "Looking Backward vs. Forward: It is impossible to see how experiences connect when looking forward. You can only connect the dots looking backward in time.",
          "Trust in the Journey: You must trust in something—your gut, destiny, life, karma—to have the confidence to follow your heart, even when it leads you off the well-worn path."
        ]
      },
      {
        id: "sec-2",
        title: "Story 2: Love and Loss",
        timestamp: 162.0,
        summary: "Jobs discusses starting Apple at age 20, getting fired publicly at 30, and how that devastating event freed him to embark on his most creative period, founding NeXT and Pixar, and returning to revitalize Apple.",
        bullets: [
          "The Gift of Failure: Getting fired replaced the heavy pressure of success with the light freedom of being a beginner again, unlocking his most creative years.",
          "Follow Your Passion: The only thing that kept him going was that he truly loved his work. Finding what you love is essential for both career and life satisfaction.",
          "Do Not Settle: If you haven't found your passion yet, keep looking. Just like matters of the heart, you will know when you find it."
        ]
      },
      {
        id: "sec-3",
        title: "Story 3: Death and Life's Destiny",
        timestamp: 280.0,
        summary: "Reflecting on his diagnosis and recovery from pancreatic cancer, Jobs urges the graduates to remember their mortality, which strips away superficial fears and leaving only what truly matters.",
        bullets: [
          "Death as a Motivator: Death is the destination we all share. It clears out the old to make way for the new, acting as life's single best invention and change agent.",
          "Avoid Dogma and Opinion: Do not waste your limited time living someone else's life or being trapped by other people's thinking. Do not let external noise drown out your inner voice.",
          "Stay Hungry, Stay Foolish: The famous farewell message of the Whole Earth Catalog serves as his final advice to the graduates—to remain constantly curious, eager, and willing to take risks."
        ]
      }
    ]
  }
];
